#!/data/data/com.termux/files/usr/bin/env bash
source "${PLEIADES_TERMUX_LIB:-}" 2>/dev/null || true
# pleiades-mcp-converters.sh — repo2mcp, paper2mcp, openapi2mcp converters
# Tasks #22, #23, #24
#
# Third-party attributions:
#   fastmcp          jlowin          MIT   https://github.com/jlowin/fastmcp
#   fastapi_mcp      tadata-org      MIT   https://github.com/tadata-org/fastapi_mcp
#   openapi-mcp-codegen cnoe-io      Apache-2.0  https://github.com/cnoe-io/openapi-mcp-codegen
#   jcodemunch-mcp   jgravelle       MIT   https://github.com/jgravelle/jcodemunch-mcp
#   paper2code       PrathamLearnsToCode MIT https://github.com/PrathamLearnsToCode/paper2code
#
# This script generates wrappers that call these tools; it does not vendor their source.
# Generated Python uses the fastmcp/fastapi_mcp APIs as documented upstream.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLEIADES_CONTAINER_ROOT="${PLEIADES_CONTAINER_ROOT:-$(dirname "$SCRIPT_DIR")}"
PLEIADES_REPO_ROOT="${PLEIADES_REPO_ROOT:-$(dirname "$PLEIADES_CONTAINER_ROOT")}"

VERSION="1.0.0"
MCP_OUT="/var/lib/pleiades/mcp-servers"
LOG_FILE="/var/log/pleiades/mcp-converters.log"
mkdir -p "$MCP_OUT" "$(dirname "$LOG_FILE")" 2>/dev/null || true

log() { printf '[%s] [mcp-converters] %s\n' "$(date -u +%H:%M:%S)" "$*" | tee -a "$LOG_FILE" >&2; }
die() { log "ERROR: $*"; exit 1; }

# ── FastMCP server template ───────────────────────────────────────────────────
_fastmcp_template() {
    local name="$1" description="$2" tools_body="$3"
    cat << PYEOF
"""${description}
Auto-generated by pleiades-mcp-converters (pleiades team)
"""
from fastmcp import FastMCP

mcp = FastMCP("${name}")

${tools_body}

if __name__ == "__main__":
    mcp.run()
PYEOF
}

# ── repo2mcp ──────────────────────────────────────────────────────────────────
repo2mcp() {
    local repo_url="${1:-}"
    [[ -z "$repo_url" ]] && die "Usage: repo2mcp <github-url>"

    local slug; slug=$(basename "$repo_url" .git | tr '[:upper:]' '[:lower:]' | tr -cs 'a-z0-9' '_')
    local out_dir="$MCP_OUT/$slug"
    mkdir -p "$out_dir"
    log "repo2mcp: $repo_url → $out_dir"

    # Step 1: clone to temp
    local tmpdir; tmpdir=$(mktemp -d)
    git clone --depth=1 "$repo_url" "$tmpdir/repo" 2>/dev/null || { log "WARN: clone failed — using URL only"; }

    # Step 2: pack context with repomix or gitingest
    local context_file="$out_dir/context.txt"
    if command -v repomix &>/dev/null; then
        repomix --output "$context_file" "$tmpdir/repo" 2>/dev/null \
            || find "$tmpdir/repo" -name "*.py" -o -name "*.ts" -o -name "*.js" | head -20 | xargs cat > "$context_file" 2>/dev/null || true
    elif command -v gitingest &>/dev/null; then
        gitingest "$repo_url" --output "$context_file" 2>/dev/null || true
    else
        # Fallback: concatenate source files
        find "$tmpdir/repo" \( -name "*.py" -o -name "*.ts" -o -name "*.js" \) -not -path "*/node_modules/*" \
            | head -30 | xargs cat > "$context_file" 2>/dev/null || true
        log "WARN: repomix/gitingest not found — using file concatenation fallback"
        log "  Install: npm install -g repomix  OR  pip install gitingest"
    fi
    rm -rf "$tmpdir"

    # Step 3: generate MCP server
    local server_file="$out_dir/server.py"
    if [[ -x /usr/local/bin/pleiades-llm ]] && [[ -f "$context_file" ]]; then
        local prompt
        prompt="Repository: $slug
Context:
$(head -200 "$context_file")

Generate a FastMCP server (Python, using 'from fastmcp import FastMCP') that exposes the
3-5 most useful functions from this codebase as MCP tools with @mcp.tool() decorator.
Include docstrings describing parameters. Output only Python code."
        echo "$prompt" | /usr/local/bin/pleiades-llm --mode=re 2>/dev/null > "$server_file" \
            || _write_stub_server "$slug" "$server_file"
    else
        _write_stub_server "$slug" "$server_file"
    fi

    _write_mcp_readme "$slug" "$repo_url" "repo" "$out_dir"
    log "repo2mcp complete: $out_dir"
    echo "$out_dir"
}

# ── paper2mcp ─────────────────────────────────────────────────────────────────
paper2mcp() {
    local arxiv_id="${1:-}"
    [[ -z "$arxiv_id" ]] && die "Usage: paper2mcp <arxiv-id>  (e.g. 2605.08419)"

    local slug="paper-${arxiv_id//./_}"
    local out_dir="$MCP_OUT/$slug"
    mkdir -p "$out_dir"
    log "paper2mcp: arXiv:$arxiv_id → $out_dir"

    # Step 1: fetch PDF text
    local pdf_url="https://arxiv.org/pdf/${arxiv_id}.pdf"
    local pdf_file="$out_dir/${arxiv_id}.pdf"
    local text_file="$out_dir/paper.txt"

    if command -v wget &>/dev/null; then
        wget -q -O "$pdf_file" "$pdf_url" 2>/dev/null || log "WARN: PDF download failed"
    elif command -v curl &>/dev/null; then
        curl -fsSL -o "$pdf_file" "$pdf_url" 2>/dev/null || log "WARN: PDF download failed"
    fi

    # Step 2: extract text
    if [[ -f "$pdf_file" ]]; then
        if command -v pdftotext &>/dev/null; then
            pdftotext "$pdf_file" "$text_file" 2>/dev/null || true
        elif python3 -c "import PyPDF2" 2>/dev/null; then
            python3 - "$pdf_file" "$text_file" << 'PYEOF'
import sys
import PyPDF2
with open(sys.argv[1], 'rb') as f:
    r = PyPDF2.PdfReader(f)
    text = '\n'.join(p.extract_text() or '' for p in r.pages)
with open(sys.argv[2], 'w') as f:
    f.write(text)
PYEOF
        else
            log "WARN: no PDF extractor (pdftotext or PyPDF2) — using raw download"
            cp "$pdf_file" "$text_file"
        fi
    fi

    # Step 3: check for existing paper2code output
    local p2c_dir="${PLEIADES_PAPER2CODE_WORK:-${PLEIADES_REPO_ROOT}/.paper2code_work}"
    local existing; existing=$(find "$p2c_dir" -name "${arxiv_id}*" -type f 2>/dev/null | head -1 || true)
    if [[ -n "$existing" ]]; then
        log "Found paper2code output: $existing"
        cp "$existing" "$out_dir/paper2code_impl.py" 2>/dev/null || true
    fi

    # Step 4: generate MCP server wrapping the algorithm
    local server_file="$out_dir/server.py"
    if [[ -x /usr/local/bin/pleiades-llm ]] && [[ -f "$text_file" ]]; then
        local prompt
        prompt="arXiv paper ID: $arxiv_id
Paper text (first 300 lines):
$(head -300 "$text_file" 2>/dev/null)

1. Identify the primary algorithm/contribution of this paper.
2. Generate a FastMCP server (Python) with @mcp.tool() exposing the main algorithm.
3. Include type hints and docstrings. Output only Python code."
        echo "$prompt" | /usr/local/bin/pleiades-llm 2>/dev/null > "$server_file" \
            || _write_stub_server "paper_${arxiv_id//./_}" "$server_file"
    else
        _write_stub_server "paper_${arxiv_id//./_}" "$server_file"
    fi

    _write_mcp_readme "$slug" "https://arxiv.org/abs/$arxiv_id" "paper" "$out_dir"
    log "paper2mcp complete: $out_dir"
    echo "$out_dir"
}

# ── openapi2mcp ───────────────────────────────────────────────────────────────
openapi2mcp() {
    local spec_file="${1:-}"
    [[ -z "$spec_file" ]] && die "Usage: openapi2mcp <openapi-spec.yaml|.json>"
    [[ -f "$spec_file" ]] || die "Spec file not found: $spec_file"

    local slug; slug=$(basename "$spec_file" | sed 's/\.[^.]*$//' | tr '[:upper:]' '[:lower:]' | tr -cs 'a-z0-9' '_')
    slug="api-$slug"
    local out_dir="$MCP_OUT/$slug"
    mkdir -p "$out_dir"
    log "openapi2mcp: $spec_file → $out_dir"

    # Step 1: try fastapi-mcp or openapi-mcp-codegen
    if python3 -c "import fastapi_mcp" 2>/dev/null; then
        log "Using fastapi-mcp"
        python3 - "$spec_file" "$out_dir/server.py" << 'PYEOF'
import sys, json, yaml, re
from pathlib import Path

spec_path = Path(sys.argv[1])
out_path = Path(sys.argv[2])

text = spec_path.read_text()
spec = json.loads(text) if spec_path.suffix == '.json' else yaml.safe_load(text)

title = spec.get('info', {}).get('title', 'api').replace(' ', '_').lower()
tools = []
for path, methods in spec.get('paths', {}).items():
    for method, op in methods.items():
        if method in ('get', 'post', 'put', 'delete', 'patch'):
            op_id = op.get('operationId', f"{method}_{re.sub(r'[^a-z0-9]', '_', path.lower())}")
            desc = op.get('summary', op.get('description', 'API operation'))
            params = op.get('parameters', [])
            param_str = ', '.join(p['name'] for p in params if p.get('in') in ('query', 'path'))
            tools.append(f'''
@mcp.tool()
def {op_id}({param_str}) -> dict:
    """{desc}

    Endpoint: {method.upper()} {path}
    """
    import httpx
    # TODO: configure base_url from environment
    base_url = os.environ.get('API_BASE_URL', '')
    resp = httpx.{method}(f"{{base_url}}{path}", params={{{', '.join(f'"{p["name"]}": {p["name"]}' for p in params if p.get("in") == "query")}}})
    return resp.json()
''')

server_code = f"""import os
from fastmcp import FastMCP
import httpx

mcp = FastMCP("{title}")

{"".join(tools) if tools else "# No endpoints parsed — check spec format"}

if __name__ == "__main__":
    mcp.run()
"""
out_path.write_text(server_code)
print(f"Generated {len(tools)} tool(s)")
PYEOF
    else
        log "WARN: fastapi-mcp not available — writing annotated stub"
        log "  Install: pip install fastapi-mcp  OR  npm install -g openapi-mcp-codegen"
        _write_openapi_stub "$spec_file" "$slug" "$out_dir/server.py"
    fi

    _write_mcp_readme "$slug" "$spec_file" "openapi" "$out_dir"
    log "openapi2mcp complete: $out_dir"
    echo "$out_dir"
}

# ── Helpers ───────────────────────────────────────────────────────────────────
_write_stub_server() {
    local name="$1" out="$2"
    cat > "$out" << PYEOF
"""MCP server stub for: $name
Generated by pleiades-mcp-converters — LLM not available, manual implementation required.
"""
from fastmcp import FastMCP

mcp = FastMCP("$name")

@mcp.tool()
def analyze(input: str) -> str:
    """TODO: implement main tool for $name"""
    raise NotImplementedError("Implement this tool")

if __name__ == "__main__":
    mcp.run()
PYEOF
}

_write_openapi_stub() {
    local spec="$1" name="$2" out="$3"
    cat > "$out" << PYEOF
"""MCP server for OpenAPI spec: $spec
Generated by pleiades-mcp-converters
Run: pip install fastapi-mcp httpx && python server.py
"""
from fastmcp import FastMCP
import httpx, os

mcp = FastMCP("$name")
BASE_URL = os.environ.get("API_BASE_URL", "https://api.example.com")

@mcp.tool()
def api_call(endpoint: str, method: str = "GET", body: dict = None) -> dict:
    """Generic API caller — replace with specific tools from $spec"""
    resp = httpx.request(method, f"{BASE_URL}{endpoint}", json=body)
    return resp.json()

if __name__ == "__main__":
    mcp.run()
PYEOF
}

_write_mcp_readme() {
    local name="$1" source="$2" type="$3" dir="$4"
    cat > "$dir/README.md" << MDEOF
# MCP Server: $name

**Type:** $type
**Source:** $source
**Generated:** $(date -u +%Y-%m-%dT%H:%M:%SZ)

## Usage

\`\`\`bash
pip install fastmcp
python server.py
\`\`\`

## Integration

Add to Claude config:
\`\`\`json
{"mcpServers": {"$name": {"command": "python", "args": ["$(realpath "$dir")/server.py"]}}}
\`\`\`
MDEOF
}

# ── CLI ───────────────────────────────────────────────────────────────────────
main() {
    local cmd="${1:-help}"; shift || true
    case "$cmd" in
        repo2mcp)     repo2mcp "$@" ;;
        paper2mcp)    paper2mcp "$@" ;;
        openapi2mcp)  openapi2mcp "$@" ;;
        version)      echo "pleiades-mcp-converters $VERSION" ;;
        help|--help|-h)
            cat << 'HELP'
pleiades-mcp-converters — Convert repos/papers/APIs to MCP servers

Commands:
  repo2mcp <github-url>        GitHub repo → FastMCP server
  paper2mcp <arxiv-id>         arXiv paper → FastMCP server
  openapi2mcp <spec.yaml>      OpenAPI spec → FastMCP server
  version

Examples:
  pleiades-mcp-converters repo2mcp https://github.com/example/tool
  pleiades-mcp-converters paper2mcp 2605.08419
  pleiades-mcp-converters openapi2mcp ./api/openapi.yaml
HELP
            ;;
        *) die "Unknown command: $cmd" ;;
    esac
}

main "$@"
