#!/data/data/com.termux/files/usr/bin/env bash
source "${PLEIADES_TERMUX_LIB:-}" 2>/dev/null || true
# pleiades-fuzz.sh — Pleiades Team fuzzing pipeline
# Stage 1: static analysis → Stage 2: LLM harness gen → Stage 3: AFL++ fuzz
# Stage 4: crash validation → Stage 5: LLM patch proposal
# Task #16: Implement vulnerability discovery + fuzzing loop
set -euo pipefail

VERSION="1.0.0"
LOG_FILE="/var/log/pleiades/fuzz.log"
FUZZ_STATE="/var/lib/pleiades/fuzz-campaigns"
LLM_BIN="/usr/local/bin/pleiades-llm"
FIFO="/run/pleiades/pleiades-nexus_fifo"

mkdir -p "$(dirname "$LOG_FILE")" 2>/dev/null || true

log()   { local m="[$(date -u +%H:%M:%S)] [pleiades-fuzz] [$$] $*"; printf '%s\n' "$m" | tee -a "$LOG_FILE" >&2; }
event() { printf '%s\n' "$1" >> "$FIFO" 2>/dev/null || true; }
die()   { log "ERROR: $*"; exit 1; }

# ─── Stage 1: Static analysis ─────────────────────────────────────────────────
stage1_static_analysis() {
    local binary="$1"
    log "Stage 1: static analysis — $binary"

    {
        echo "=== Binary Info ==="
        file "$binary" 2>/dev/null
        echo ""
        echo "=== Security Properties ==="
        # checksec-like using readelf/objdump
        if command -v checksec &>/dev/null; then
            checksec --file="$binary" 2>/dev/null || true
        else
            echo "PIE: $(readelf -h "$binary" 2>/dev/null | grep -c 'Type:.*DYN' || echo 0)"
            echo "RELRO: $(readelf -l "$binary" 2>/dev/null | grep -c GNU_RELRO || echo 0)"
            echo "STACK_CANARY: $(nm "$binary" 2>/dev/null | grep -c '__stack_chk_fail' || echo 0)"
            echo "NX: $(readelf -l "$binary" 2>/dev/null | grep -c 'GNU_STACK.*RW ' || echo unknown)"
        fi

        echo ""
        echo "=== Input Sinks (dangerous functions) ==="
        nm -D "$binary" 2>/dev/null | grep -E "gets|scanf|sprintf|strcpy|strcat|system|popen|execv|memcpy" || \
        objdump -T "$binary" 2>/dev/null | grep -E "gets|scanf|sprintf|strcpy|strcat|system|popen|execv|memcpy" || true

        echo ""
        echo "=== Format String Candidates ==="
        objdump -d "$binary" 2>/dev/null | grep -B2 "printf\|fprintf\|syslog" | head -40 || true

        echo ""
        echo "=== Interesting Strings ==="
        strings "$binary" 2>/dev/null | grep -E "%[sdifpx]|format|input|parse|read|argv|stdin" | head -30 || true

        if command -v r2 &>/dev/null; then
            echo ""
            echo "=== radare2: input vectors ==="
            r2 -q -e scr.color=0 -e log.level=0 \
               -c "aaa; afl~read,fread,fgets,scanf,recv,recvfrom; afl~gets,sprintf,memcpy" \
               "$binary" 2>/dev/null | head -50 || true
        fi
    }
}

# ─── Stage 2: LLM harness generation ──────────────────────────────────────────
stage2_generate_harness() {
    local binary="$1"
    local static_out="$2"
    local harness_file="$3"
    local binary_name; binary_name=$(basename "$binary")

    log "Stage 2: LLM harness generation — $harness_file"

    if [[ ! -x "$LLM_BIN" ]]; then
        log "WARN: $LLM_BIN not found — writing template harness"
        cat > "$harness_file" << HARNESS
// AFL++ harness template for $binary_name
// Generated by pleiades-fuzz (LLM unavailable — edit manually)
// Compile: afl-gcc -o harness harness.c -L. -l$(basename "$binary" | sed 's/lib//;s/\.so.*//')
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

// TODO: include target headers and implement fuzz_target
int LLVMFuzzerTestOneInput(const uint8_t *data, size_t size) {
    if (size < 4) return 0;
    // TODO: call target function with fuzz data
    return 0;
}
HARNESS
        return 0
    fi

    local prompt
    prompt="Binary: $binary_name
Static analysis output:
$static_out

Generate a minimal AFL++ LLVMFuzzerTestOneInput harness in C that:
1. Targets the most promising input vector identified above
2. Calls the relevant function with fuzz data
3. Includes correct headers and handles segfaults gracefully
4. Is self-contained and compilable with: afl-clang-fast -o harness harness.c
Output ONLY the C code, no explanation."

    echo "$prompt" | "$LLM_BIN" --mode=fuzz 2>/dev/null > "$harness_file" \
        || { log "LLM harness generation failed — writing template"; stage2_generate_harness "$binary" "" "$harness_file"; }

    log "Harness written to $harness_file"
}

# ─── Stage 3: AFL++ fuzzing ────────────────────────────────────────────────────
stage3_fuzz() {
    local harness_src="$1"
    local campaign_dir="$2"
    local duration="${3:-3600}"  # seconds, default 1 hour

    log "Stage 3: AFL++ fuzzing — duration=${duration}s"
    mkdir -p "$campaign_dir/in" "$campaign_dir/out"

    # Seed corpus
    echo "AAAA" > "$campaign_dir/in/seed1"
    printf '\x00\x01\x02\x03' > "$campaign_dir/in/seed2"
    printf '%1000s' > "$campaign_dir/in/seed3"

    # Compile harness
    local harness_bin="$campaign_dir/harness"
    if command -v afl-clang-fast &>/dev/null; then
        afl-clang-fast -o "$harness_bin" "$harness_src" 2>/dev/null \
            || { log "WARN: afl-clang-fast failed, trying afl-gcc"; afl-gcc -o "$harness_bin" "$harness_src" 2>/dev/null || true; }
    elif command -v afl-gcc &>/dev/null; then
        afl-gcc -o "$harness_bin" "$harness_src" 2>/dev/null || true
    else
        log "WARN: no AFL++ compiler found — install dev-util/afl++"
        log "  emerge --noreplace dev-util/afl++ (or: apt-get install afl++)"
        return 1
    fi

    if [[ ! -x "$harness_bin" ]]; then
        log "WARN: harness compilation failed — skipping fuzz run"
        return 1
    fi

    log "Running afl-fuzz for ${duration}s (background)"
    timeout "$duration" afl-fuzz \
        -i "$campaign_dir/in" \
        -o "$campaign_dir/out" \
        -V "$duration" \
        -- "$harness_bin" @@ \
        2>&1 | tail -5 &
    local afl_pid=$!
    wait "$afl_pid" || true

    local crashes; crashes=$(find "$campaign_dir/out" -name "id:*" -path "*/crashes/*" 2>/dev/null | wc -l)
    local hangs; hangs=$(find "$campaign_dir/out" -name "id:*" -path "*/hangs/*" 2>/dev/null | wc -l)
    log "Fuzz run complete — crashes: $crashes, hangs: $hangs"
    echo "$crashes"
}

# ─── Stage 4: Crash validation ─────────────────────────────────────────────────
stage4_validate_crashes() {
    local harness_bin="$1"
    local campaign_dir="$2"
    local crash_report="$3"

    log "Stage 4: crash validation"
    local crash_count=0

    {
        echo "# Crash Validation Report"
        echo "Campaign: $campaign_dir"
        echo "Date: $(date -u)"
        echo ""
    } > "$crash_report"

    while IFS= read -r -d '' crash_file; do
        (( crash_count++ ))
        echo "## Crash $crash_count: $(basename "$crash_file")" >> "$crash_report"

        # Try ASAN reproduction
        if command -v asan_symbolize &>/dev/null || command -v llvm-symbolizer &>/dev/null; then
            ASAN_OPTIONS="symbolize=1:abort_on_error=0" \
                timeout 5 "$harness_bin" < "$crash_file" 2>&1 | head -20 >> "$crash_report" || true
        else
            timeout 5 "$harness_bin" < "$crash_file" 2>/dev/null; local ec=$?
            echo "Exit code: $ec" >> "$crash_report"
        fi
        echo "" >> "$crash_report"
    done < <(find "$campaign_dir/out" -name "id:*" -path "*/crashes/*" -print0 2>/dev/null | head -c 100)

    log "Validated $crash_count crash(es) — report: $crash_report"
    echo "$crash_count"
}

# ─── Stage 5: LLM patch proposal ──────────────────────────────────────────────
stage5_patch_proposal() {
    local binary="$1"
    local crash_report="$2"
    local static_out="$3"
    local patch_file="$4"

    log "Stage 5: LLM patch proposal"

    if [[ ! -x "$LLM_BIN" ]]; then
        echo "<!-- LLM patch: install pleiades-llm (task #18) and re-run -->" > "$patch_file"
        return 0
    fi

    local prompt
    prompt="Binary: $(basename "$binary")
Static analysis:
$(head -40 <<< "$static_out")

Crash report summary:
$(head -30 "$crash_report" 2>/dev/null)

Based on the crash evidence, propose a minimal security patch.
Focus on the root cause. Output only the patch or fixed function."

    echo "$prompt" | "$LLM_BIN" --mode=patch 2>/dev/null > "$patch_file" \
        || echo "<!-- patch generation failed -->" > "$patch_file"
    log "Patch proposal written to $patch_file"
}

# ─── Command: fuzz ─────────────────────────────────────────────────────────────
cmd_fuzz() {
    local binary=""
    local duration=3600
    local output=""

    for arg in "$@"; do
        case "$arg" in
            --duration=*) duration="${arg#--duration=}" ;;
            --output=*)   output="${arg#--output=}" ;;
            --*)          die "Unknown flag: $arg" ;;
            *)            binary="$arg" ;;
        esac
    done

    [[ -z "$binary" ]] && die "Usage: pleiades-fuzz <binary> [--duration=N] [--output=dir]"
    [[ -f "$binary" ]] || die "Binary not found: $binary"

    local slug; slug=$(basename "$binary" | tr '[:upper:]' '[:lower:]' | tr -cs 'a-z0-9' '_')
    local ts; ts=$(date -u +%Y%m%dT%H%M%S)
    local campaign_dir="${output:-$FUZZ_STATE/${slug}_$ts}"
    mkdir -p "$campaign_dir"

    event "FUZZ_START|pleiades-fuzz|$(basename "$binary")|$(date -u +%s)"
    log "Campaign: $campaign_dir"

    local static_out; static_out=$(stage1_static_analysis "$binary")
    echo "$static_out" > "$campaign_dir/static_analysis.txt"

    local harness_src="$campaign_dir/harness.c"
    stage2_generate_harness "$binary" "$static_out" "$harness_src"

    local crash_count=0
    if stage3_fuzz "$harness_src" "$campaign_dir" "$duration"; then
        local crash_report="$campaign_dir/crash_report.md"
        local harness_bin="$campaign_dir/harness"
        crash_count=$(stage4_validate_crashes "$harness_bin" "$campaign_dir" "$crash_report")
        if (( crash_count > 0 )); then
            stage5_patch_proposal "$binary" "$crash_report" "$static_out" "$campaign_dir/patch_proposal.md"
        fi
    fi

    event "FUZZ_DONE|pleiades-fuzz|$(basename "$binary")|crashes=$crash_count"
    log ""
    log "=== Campaign complete ==="
    log "  campaign: $campaign_dir"
    log "  crashes:  $crash_count"
    log "  harness:  $harness_src"
    [[ -f "$campaign_dir/crash_report.md" ]] && log "  report:   $campaign_dir/crash_report.md"
    [[ -f "$campaign_dir/patch_proposal.md" ]] && log "  patch:    $campaign_dir/patch_proposal.md"
}

# ─── Command: install-deps ─────────────────────────────────────────────────────
cmd_install_deps() {
    log "Installing fuzzing dependencies"
    if command -v emerge &>/dev/null; then
        emerge --ask=n --noreplace dev-util/afl++ dev-util/lcov || true
    elif command -v apt-get &>/dev/null; then
        apt-get install -y afl++ llvm clang || true
    fi
    log "Verify: afl-fuzz --help"
}

# ─── Entrypoint ────────────────────────────────────────────────────────────────
main() {
    local cmd="${1:-help}"; shift || true
    case "$cmd" in
        fuzz)          cmd_fuzz "$@" ;;
        install-deps)  cmd_install_deps ;;
        version)       echo "pleiades-fuzz $VERSION" ;;
        help|--help|-h)
            cat << 'HELP'
pleiades-fuzz — Pleiades Team Vulnerability Discovery + Fuzzing Loop

Commands:
  fuzz <binary> [opts]   Full pipeline: static analysis → harness → AFL++ → crash validation → patch
  install-deps           Install AFL++, llvm, clang
  version                Show version

Options for fuzz:
  --duration=N           Fuzz duration in seconds (default: 3600 = 1 hour)
  --output=dir           Campaign output directory

Examples:
  pleiades-fuzz fuzz /usr/bin/target --duration=300
  pleiades-fuzz fuzz ./vulnerable.elf --output=/tmp/campaign1
HELP
            ;;
        *) die "Unknown command: $cmd. Run pleiades-fuzz help" ;;
    esac
}

main "$@"
