{
  "schema": "pleiades-tool-manifest-v1",
  "root": "__PLEIADES_ROOT__/tools",
  "tools": [
    {"id": "CoEvoSkills",          "path": "__PLEIADES_ROOT__/tools/CoEvoSkills"},
    {"id": "CodexSaver",           "path": "__PLEIADES_ROOT__/tools/CodexSaver"},
    {"id": "DeepCode",             "path": "__PLEIADES_ROOT__/tools/DeepCode"},
    {"id": "FEX",                  "path": "__PLEIADES_ROOT__/tools/FEX"},
    {"id": "LUKSbox",              "path": "__PLEIADES_ROOT__/tools/LUKSbox"},
    {"id": "MemOS",                "path": "__PLEIADES_ROOT__/tools/MemOS"},
    {"id": "OpenHands",            "path": "__PLEIADES_ROOT__/tools/OpenHands"},
    {"id": "Photo-agents",         "path": "__PLEIADES_ROOT__/tools/Photo-agents"},
    {"id": "ShadowCat",            "path": "__PLEIADES_ROOT__/tools/ShadowCat"},
    {"id": "SkillGen",             "path": "__PLEIADES_ROOT__/tools/SkillGen"},
    {"id": "SkillX",               "path": "__PLEIADES_ROOT__/tools/SkillX"},
    {"id": "agent-oss",            "path": "__PLEIADES_ROOT__/tools/agent-oss"},
    {"id": "agent-rules-books",    "path": "__PLEIADES_ROOT__/tools/agent-rules-books"},
    {"id": "ai-memory",            "path": "__PLEIADES_ROOT__/tools/ai-memory"},
    {"id": "angr",                 "path": "__PLEIADES_ROOT__/tools/angr"},
    {"id": "box64",                "path": "__PLEIADES_ROOT__/tools/box64"},
    {"id": "btype",                "path": "__PLEIADES_ROOT__/tools/btype"},
    {"id": "chorus",               "path": "__PLEIADES_ROOT__/tools/chorus"},
    {"id": "claude-p",             "path": "__PLEIADES_ROOT__/tools/claude-p"},
    {"id": "codegraph",            "path": "__PLEIADES_ROOT__/tools/codegraph"},
    {"id": "codeindex",            "path": "__PLEIADES_ROOT__/tools/codeindex"},
    {"id": "continual-harness",    "path": "__PLEIADES_ROOT__/tools/continual-harness"},
    {"id": "ddisasm",              "path": "__PLEIADES_ROOT__/tools/ddisasm"},
    {"id": "elephant-agent",       "path": "__PLEIADES_ROOT__/tools/elephant-agent"},
    {"id": "fastapi_mcp",          "path": "__PLEIADES_ROOT__/tools/fastapi_mcp"},
    {"id": "fastmcp",              "path": "__PLEIADES_ROOT__/tools/fastmcp"},
    {"id": "files-sdk",            "path": "__PLEIADES_ROOT__/tools/files-sdk"},
    {"id": "ghidra",               "path": "__PLEIADES_ROOT__/tools/ghidra"},
    {"id": "gitingest",            "path": "__PLEIADES_ROOT__/tools/gitingest"},
    {"id": "hermes-agent-self-evolution", "path": "__PLEIADES_ROOT__/tools/hermes-agent-self-evolution"},
    {"id": "jcodemunch-mcp",       "path": "__PLEIADES_ROOT__/tools/jcodemunch-mcp"},
    {"id": "mcsema",               "path": "__PLEIADES_ROOT__/tools/mcsema"},
    {"id": "openapi-mcp-codegen",  "path": "__PLEIADES_ROOT__/tools/openapi-mcp-codegen"},
    {"id": "opensquilla",          "path": "__PLEIADES_ROOT__/tools/opensquilla"},
    {"id": "paper2code",           "path": "__PLEIADES_ROOT__/tools/paper2code"},
    {"id": "piia-engram",          "path": "__PLEIADES_ROOT__/tools/piia-engram"},
    {"id": "remill",               "path": "__PLEIADES_ROOT__/tools/remill"},
    {"id": "repomix",              "path": "__PLEIADES_ROOT__/tools/repomix"},
    {"id": "resym",                "path": "__PLEIADES_ROOT__/tools/resym"},
    {"id": "retrowrite",           "path": "__PLEIADES_ROOT__/tools/retrowrite"}
  ]
}
